In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [10]:
data = pd.read_csv("/home/smol/Music/ml/mnist_rawdoggin/mnist_train.csv")


In [14]:
data.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [12]:
data = np.array(data)
m, n  = data.shape
print(data)
print()
np.random.shuffle(data)
print(data)

data_dev =  data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

[[3 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 [4 0 0 ... 0 0 0]
 ...
 [6 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

[[2 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 ...
 [3 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]]


In [ ]:
def init_prams():
    W1 = np.random.rand(10, 784) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1,b1, W2, b2

def ReLU(Z):
    return np.maximum(0,Z)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

def forward_prop(W1,b1,W2,b2,X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) +b2
    A2 = softmax(Z2)    
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0
 
def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/ m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2,2)
    dZ1 = W2.T.dot(dZ2)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1,2)
    return  dW1, db1, dW2 , db2

def update_params(W1, b1, W2, b2, dW1, db1 , dW2, db2,alpha):
    
    W1 = W1 - alhttps://github.com/smolvamp/MNIST-based-digit-recognition.gitpha * db1
    return W1, b1, W2,  b2


In [13]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_prams()
    for i in range(iterations):
        Z1, A1 ,Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1 , dW2, db2,alpha )
        if i % 50 == 0:
            print("Iteration:", i)
            print("Accuracy:", get_accuracy(get_predictions(A2),Y))
    return W1, b1, W2, b2

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.1)